remove completely prints
ufcg-lsd/asperathos-manager pull request #100
Opened 2019-12-02 19:06 UTC by javanlacerda

2019-12-12 18:06 UTC, joseims approved these changes

2020-01-29 18:12 UTC, liliarsampaio requested changes
Check de failures, please.

2020-02-04 15:52 UTC, javanlacerda commented
> Check de failures, please.

Done

2020-02-28 12:57 UTC, DiegoGamaV approved these changes

2020-04-29 22:56 UTC, merged